[build]
  command = "npm install && npm run build"
  publish = "public" # O la carpeta donde están los archivos que quieres publicar

[build.environment]
  NODE_VERSION = "14" # Asegúrate de usar una versión compatible de Node.js
